on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set a static tag name
      - name: Set static tag and release name
        id: set_static_name
        run: |
          echo "::set-output name=tag::static-release"
          echo "::set-output name=release_name::Static Release"

      # Check if tag exists and delete it if it does
      - name: Delete existing tag
        run: |
          if git rev-parse ${{ steps.set_static_name.outputs.tag }} >/dev/null 2>&1; then
            git tag -d ${{ steps.set_static_name.outputs.tag }}
            git push --delete origin ${{ steps.set_static_name.outputs.tag }}
          fi

      # Create or move the tag to the current commit
      - name: Create or move tag
        run: |
          git tag -fa ${{ steps.set_static_name.outputs.tag }} -m "${{ steps.set_static_name.outputs.release_name }}"
          git push origin ${{ steps.set_static_name.outputs.tag }} --force

      # Create or update the release
      - name: Create or update release
        id: create_or_update_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_static_name.outputs.tag }}
          release_name: ${{ steps.set_static_name.outputs.release_name }}
          body: "Several Changes in this Release"
          draft: false
          prerelease: false
